<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EftToolkit.Audio</RootNamespace>
    <AssemblyName>EftToolkit.Audio</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EftToolkit.Core\EftToolkit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" />
  </ItemGroup>

</Project>
