<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>EftToolkit.App</RootNamespace>
    <AssemblyName>EftToolkit.App</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EftToolkit.Core\EftToolkit.Core.csproj" />
    <ProjectReference Include="..\EftToolkit.Display\EftToolkit.Display.csproj" />
    <ProjectReference Include="..\EftToolkit.Audio\EftToolkit.Audio.csproj" />
    <ProjectReference Include="..\EftToolkit.Platform.Windows\EftToolkit.Platform.Windows.csproj" />
  </ItemGroup>

</Project>
